import type { Asset, AssetHierarchyNode, Document, InterventionLog, StatusCount } from './types';

export const mockAssets: Asset[] = [
  {
    id: 'AST-001',
    name: 'City Office Complex',
    assetClass: 'buildings',
    type: 'Office Building',
    location: 'Downtown District',
    status: 'active',
    condition: 'good',
    value: 7350000,
    acquisitionDate: '2015-03-15',
    latitude: 40.7128,
    longitude: -74.006,
    responsibleUnit: 'Facilities Management',
    usefulLife: 50,
    remainingLife: 39,
    lastInspection: '2024-01-15',
  },
  {
    id: 'AST-002',
    name: 'Parking Lot A',
    assetClass: 'land',
    type: 'Parking Facility',
    location: 'Downtown District',
    status: 'active',
    condition: 'fair',
    value: 890000,
    acquisitionDate: '2010-06-20',
    latitude: 40.7138,
    longitude: -74.008,
    responsibleUnit: 'Property Management',
    usefulLife: 30,
    remainingLife: 14,
    lastInspection: '2023-11-20',
  },
  {
    id: 'AST-003',
    name: 'HVAC Unit #101',
    assetClass: 'equipment',
    type: 'HVAC System',
    location: 'City Office Complex - Floor 1',
    status: 'under-maintenance',
    condition: 'fair',
    value: 45000,
    acquisitionDate: '2018-09-10',
    latitude: 40.7128,
    longitude: -74.006,
    parentId: 'AST-001',
    responsibleUnit: 'Maintenance',
    usefulLife: 15,
    remainingLife: 7,
    lastInspection: '2024-02-01',
    manufacturer: 'Carrier',
    serialNumber: 'HV-20094',
    installedDate: '2018-09-15',
  },
  {
    id: 'AST-004',
    name: 'Fleet Vehicle #12',
    assetClass: 'vehicles',
    type: 'Utility Vehicle',
    location: 'Motor Pool',
    status: 'active',
    condition: 'good',
    value: 35000,
    acquisitionDate: '2022-01-15',
    latitude: 40.715,
    longitude: -74.01,
    responsibleUnit: 'Fleet Management',
    usefulLife: 10,
    remainingLife: 8,
    lastInspection: '2024-01-30',
  },
  {
    id: 'AST-005',
    name: 'Server Room Equipment',
    assetClass: 'ict',
    type: 'Data Center',
    location: 'City Office Complex - Basement',
    status: 'active',
    condition: 'excellent',
    value: 250000,
    acquisitionDate: '2023-05-01',
    latitude: 40.7128,
    longitude: -74.006,
    parentId: 'AST-001',
    responsibleUnit: 'IT Department',
    usefulLife: 7,
    remainingLife: 6,
    lastInspection: '2024-02-15',
  },
  {
    id: 'AST-006',
    name: 'Conference Room Furniture',
    assetClass: 'furniture',
    type: 'Office Furniture',
    location: 'City Office Complex - Floor 2',
    status: 'active',
    condition: 'good',
    value: 15000,
    acquisitionDate: '2020-03-10',
    latitude: 40.7128,
    longitude: -74.006,
    parentId: 'AST-001',
    responsibleUnit: 'Office Services',
    usefulLife: 10,
    remainingLife: 6,
  },
  {
    id: 'AST-007',
    name: 'Old Warehouse',
    assetClass: 'buildings',
    type: 'Storage Facility',
    location: 'Industrial Zone',
    status: 'decommissioned',
    condition: 'poor',
    value: 120000,
    acquisitionDate: '1995-08-20',
    latitude: 40.72,
    longitude: -74.015,
    responsibleUnit: 'Property Management',
    usefulLife: 40,
    remainingLife: 0,
    lastInspection: '2023-06-15',
  },
  {
    id: 'AST-008',
    name: 'Projector - Room 101',
    assetClass: 'ict',
    type: 'AV Equipment',
    location: 'City Office Complex - Room 101',
    status: 'active',
    condition: 'good',
    value: 2500,
    acquisitionDate: '2020-11-15',
    latitude: 40.7128,
    longitude: -74.006,
    parentId: 'AST-001',
    responsibleUnit: 'IT Department',
    usefulLife: 5,
    remainingLife: 1,
    installedDate: '2020-11-20',
  },
];

export const mockHierarchy: AssetHierarchyNode[] = [
  {
    id: 'city-office',
    name: 'City Office Complex',
    type: 'building',
    expanded: true,
    children: [
      {
        id: 'building-a',
        name: 'Building A',
        type: 'building',
        expanded: true,
        children: [
          {
            id: 'floor-1',
            name: 'Floor 1',
            type: 'floor',
            expanded: true,
            children: [
              {
                id: 'room-101',
                name: 'Room 101',
                type: 'room',
                children: [
                  { id: 'hvac-101', name: 'HVAC Unit', type: 'equipment' },
                  { id: 'projector-101', name: 'Projector', type: 'equipment' },
                ],
              },
              {
                id: 'room-102',
                name: 'Room 102',
                type: 'room',
                children: [
                  { id: 'network-rack', name: 'Network Rack', type: 'equipment' },
                ],
              },
            ],
          },
          {
            id: 'floor-2',
            name: 'Floor 2',
            type: 'floor',
            children: [
              { id: 'room-201', name: 'Room 201', type: 'room' },
              { id: 'room-202', name: 'Room 202', type: 'room' },
            ],
          },
        ],
      },
    ],
  },
];

export const mockDocuments: Document[] = [
  {
    id: 'DOC-001',
    assetId: 'AST-001',
    name: 'Property_Deed.pdf',
    type: 'title',
    uploadDate: '2024-01-15',
    size: '2.4 MB',
  },
  {
    id: 'DOC-002',
    assetId: 'AST-001',
    name: 'Building_Plan.pdf',
    type: 'plan',
    uploadDate: '2024-01-10',
    size: '15.8 MB',
  },
  {
    id: 'DOC-003',
    assetId: 'AST-003',
    name: 'Maintenance_Report.docx',
    type: 'maintenance',
    uploadDate: '2024-02-01',
    size: '1.2 MB',
  },
  {
    id: 'DOC-004',
    assetId: 'AST-003',
    name: 'Warranty_Certificate.jpg',
    type: 'warranty',
    uploadDate: '2018-09-15',
    size: '856 KB',
  },
  {
    id: 'DOC-005',
    assetId: 'AST-001',
    name: 'Inspection_Certificate.doc',
    type: 'permit',
    uploadDate: '2024-01-20',
    size: '3.1 MB',
  },
  {
    id: 'DOC-006',
    assetId: 'AST-001',
    name: 'LeaseAgreement.pdf',
    type: 'title',
    uploadDate: '2023-06-15',
    size: '4.2 MB',
  },
];

export const mockInterventions: InterventionLog[] = [
  {
    id: 'INT-001',
    date: '2024-02-15',
    action: 'Repair HVAC Unit',
    description: 'Replaced compressor and recharged refrigerant',
    status: 'completed',
  },
  {
    id: 'INT-002',
    date: '2024-02-20',
    action: 'Roof Inspection',
    description: 'Annual roof inspection and minor repairs',
    status: 'completed',
  },
  {
    id: 'INT-003',
    date: '2024-03-01',
    action: 'Boiler Inspection',
    description: 'Scheduled boiler safety inspection',
    status: 'in-progress',
  },
  {
    id: 'INT-004',
    date: '2024-03-15',
    action: 'System Upgrade',
    description: 'Upgrade security system firmware',
    status: 'scheduled',
  },
  {
    id: 'INT-005',
    date: '2024-01-10',
    action: 'Fire Extinguisher Check',
    description: 'Monthly fire safety equipment inspection',
    status: 'overdue',
  },
];

export const mockStatusCounts: StatusCount = {
  planned: 35,
  active: 742,
  underMaintenance: 128,
  decommissioned: 45,
  disposed: 30,
};

export const conditionTrendData = [
  { month: 'Jan', excellent: 65, good: 75, fair: 45, poor: 15 },
  { month: 'Feb', excellent: 68, good: 72, fair: 48, poor: 12 },
  { month: 'Mar', excellent: 70, good: 70, fair: 50, poor: 10 },
  { month: 'Apr', excellent: 65, good: 75, fair: 45, poor: 15 },
  { month: 'May', excellent: 72, good: 68, fair: 48, poor: 12 },
  { month: 'Jun', excellent: 75, good: 65, fair: 50, poor: 10 },
];

export const remainingLifeData = [
  { range: '0-2 yrs', count: 45 },
  { range: '2-5 yrs', count: 120 },
  { range: '5-10 yrs', count: 280 },
  { range: '10-20 yrs', count: 195 },
  { range: '20+ yrs', count: 102 },
];

export const assetClassCounts = {
  land: 825,
  buildings: 1130,
  vehicles: 245,
  ict: 520,
  equipment: 380,
  furniture: 115,
};
